# Generated by Django 5.2.5 on 2025-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='dispositivo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='riesgo',
            field=models.CharField(default='bajo', verbose_name='bajo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
